### PR TITLE
Support k8s 1.26 and update dependencies

### PR DESCRIPTION
**Pull request by ysksuzuki**
Signed-off-by: Yusuke Suzuki <yusuke-suzuki@cybozu.co.jp>

### CODE REVIEW

**Review by yokaze — APPROVED** [review]
LGTM. Please update the branch protection rule from next time when supported k8s versions are changing.

**Comment by ysksuzuki** [comment]
>  Please update the branch protection rule from next time when supported k8s versions are changing.

What is it? Can you elaborate?

**Comment by yokaze** [comment]
@ysksuzuki 
We need to pass several CIs to merge PRs to the main branch.
The configuration is written in the branch protection rule of the repository settings.

For CIs using matrix tests, the name of the matrix element appears in the list of mandatory tests.
Previously, this repository requires the following CIs
- main / End-to-End Tests (1.23.13)
- main / End-to-End Tests (1.24.7)
- main / End-to-End Tests (1.25.3)

to pass to merge PRs.

Since this PR changes the supported k8s versions, the previously-required tests are no longer run. Therefore, we need to update branch protection rule to merge this PR.
For this time I've updated this to
- main / End-to-End Tests (1.24.12),
- main / End-to-End Tests (1.25.8), and
- main / End-to-End Tests (1.26.3),

which include the names of the proposed k8s versions.

**Review by terassyi — APPROVED** [review]
LGTM

**Comment by ysksuzuki** [comment]
@yokaze Thanks for the explanation. Why do we need to rely on such branch protection settings? I think Coil also uses the matrix tests, but I haven't updated the branch protection settings as far as I know.

**Pull request merged**
